.\bin\scocl.exe GTAIV ".\projects\VC NGE\startup.c" ".\projects\VC NGE\sco\" GLOBALSEG
.\bin\scocl.exe GTAIV ".\projects\VC NGE\puzzle.c" ".\projects\VC NGE\sco\" DEBUGOUTPUT
.\bin\scocl.exe GTAIV ".\projects\VC NGE\loader_script.c" ".\projects\VC NGE\sco\" DEBUGOUTPUT
.\bin\scocl.exe GTAIV ".\projects\VC NGE\save.c" ".\projects\VC NGE\sco\" DEBUGOUTPUT
.\bin\scocl.exe GTAIV ".\projects\VC NGE\save_load.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\ambstreams.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\ambulance.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\AVERY.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\BIKE.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\bloodring.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\bmx.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\business_sale.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\COKERUN.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\conecrazy.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\CORTEZ.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\COUNT.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\CUBAN.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\DIAZ.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\firetruck.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\HAITI.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\heli.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\ICECREAM.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\intro.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\KAUFMAN.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\kickstart.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\LAWYER.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\main.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\MALIBU.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\map_bounds.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\mob_phone.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\no_save_script.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\ovalring.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\pcj.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\PHIL.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\pickups.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\pizza.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\PRON.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\PROTECT.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\rcheli.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\rcplne.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\rcrace.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\ROCK.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\side_quests.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\stadium.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\street_phone.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\STRIP.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\sunshine_garages.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\sunshine_race.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\taxi.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\traffic.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\vigilante.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\weap_sounds.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\vc_sounds.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\WORLD.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\cheats.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\sa_race1.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\sa_race2.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\sa_race3.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\sa_race4.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\sa_race5.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\sa_race6.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\packages.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\vc_jump.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\mission_complete_01.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\print_big.c" ".\projects\VC NGE\sco\"
.\bin\scocl.exe GTAIV ".\projects\VC NGE\bribestar_wanted.c" ".\projects\VC NGE\sco\"


pause