#define SCRIPTED_CUTSCENES_BEFORE_ACTUAL_CUTSCENES
#define SHORT_CUT_TAXIS
#define INVINCIBILITY_IN_DEMOLITION_MAN
#define BUSTED_WASTED_COMPATIBILITY
#define MISSION_COMPLETE_COMPATIBILITY
#define MISSION_NAME_COMPATIBILITY
#define BRIBES_STICKY_WANTED_ZONE_COMPATIBILITY
#define DISABLE_STICKY_WANTED_ZONE // Requires BRIBES_STICKY_WANTED_ZONE_COMPATIBILITY to be enabled for this to work.